import assert from 'node:assert/strict';
import vm from 'node:vm';
import {readFileSync} from 'node:fs';
const missionSource=readFileSync(new URL('../src/missions/multistage-operations-v14.js',import.meta.url),'utf8');
const streetsSource=readFileSync(new URL('../src/world/living-streets-v13-4a.js',import.meta.url),'utf8');
const source={id:'blacksite_77',name:'Dock Archive',contact:'mira',sectorId:'dock_nine',targetFaction:'iron',diff:2,operationIntelRecoveredV14:{bonus:180}};
const contact={id:'mira',name:'Mira',sectorId:'old_market',x:5,y:6,faction:'meridian',missions:[]};
const game={missionHistory:[source],journal:[],contacts:[contact],ovPlayer:{x:5,y:6},districtWorldsV133:{activeId:'old_market'},activeMission:null,day:7,heat:{meridian:3,iron:40},notoriety:0};
const handlers=[];
const root={document:{getElementById:()=>null},initCombat(){},createCombatUnits(){},checkWinLose(){},serializeGame:()=>JSON.stringify(game),loadGame:()=>true,ChromeRequiemCoreV5:{state:game},renderContactDossierV13(){},saveGame(){},changeContactTrustV13(){},startMission(){return true},logMsg(){},localStorage:{getItem:()=>null},Events:{on(name,fn){if(name==='mission:success')handlers.push(fn)}}};
root.globalThis=root;vm.runInNewContext(missionSource,root,{timeout:5000});
const api=root.CR14MultiStageOperations;
assert.equal(api.resolveLead('mira',api.pendingLeads('mira')[0].key,'disclose'),true);
const job=contact.missions.find(m=>m.intelFollowUpV14);
assert.ok(job);game.missionHistory.push({...job});game.heat.iron+=10;
handlers[0](job);
const outcome=game.journal.find(j=>j.id===`intel_outcome_${job.id}`);
assert.equal(outcome?.districtId,'dock_nine','completion records the original physical operation district');
const begin=streetsSource.indexOf('function intelDistrictAftermathV134(');
const end=streetsSource.indexOf('window.intelDistrictAftermathV134=intelDistrictAftermathV134;',begin);
assert.ok(begin>=0&&end>begin,'street pressure uses a named, exported derived aftermath function');
const calcSource=streetsSource.slice(begin,end);
const district=(id)=>({id});
const ctx={Game:game,currentWorldV134:()=>district('dock_nine')};
vm.runInNewContext(calcSource+'\nthis.calc=intelDistrictAftermathV134;',ctx,{timeout:5000});
const impact=ctx.calc(district('dock_nine'));
assert.equal(impact.securityRelief,1);assert.equal(impact.traceRelief,0);assert.equal(impact.closed,1);
assert.equal(ctx.calc(district('old_market')).closed,0,'effect belongs to target site, not contact district');
assert.equal(ctx.calc(district('undergrid')).closed,0);
assert.equal(ctx.calc(district('dock_nine')).securityRelief,1,'read-only HUD does not stack relief');
const encoded=JSON.parse(JSON.stringify(game));
ctx.Game=encoded;assert.equal(ctx.calc(district('dock_nine')).securityRelief,1,'derived effect survives schema-14 roundtrip');
ctx.Game=game;game.journal.push({...outcome});assert.equal(ctx.calc(district('dock_nine')).closed,1,'duplicate journal records cannot stack');
const actorBegin=streetsSource.indexOf('function actorThreatV134(');
const actorEnd=streetsSource.indexOf('function actorContactCheckV134(',actorBegin);
assert.ok(actorBegin>=0&&actorEnd>actorBegin);
const actorCtx={Game:game,clampV134:(v,a,b)=>Math.min(b,Math.max(a,v)),currentNeighborhoodStateV134:()=>({localHeat:20,security:4,gangPressure:3,unrest:2}),intelDistrictAftermathV134:ctx.calc};
vm.runInNewContext(streetsSource.slice(actorBegin,actorEnd)+'\nthis.threat=actorThreatV134;',actorCtx,{timeout:5000});
const patrol={type:'security'};
const before=actorCtx.threat(patrol,district('old_market'));
const after=actorCtx.threat(patrol,district('dock_nine'));
assert.ok(after<before,'physical patrol pressure is lower in the actual relieved district');
// Test the actual actor-contact gate, not only the display value: a mid-pressure
// security patrol stops intercepting the crew after its audit relay is disabled.
const checkSource=streetsSource.slice(actorEnd,streetsSource.indexOf('function advanceStreetActorsV134(',actorEnd));
let encounters=0;
actorCtx.Game={...game,notoriety:45,ovPlayer:{x:3,y:3},_v134EventOpen:false};
actorCtx.triggerActorEncounterV134=()=>{encounters++};
actorCtx.Game.heat.iron=50;
vm.runInNewContext(checkSource+'\nthis.contactCheck=actorContactCheckV134;',actorCtx,{timeout:5000});
const auditPatrol={id:'patrol1',type:'security',x:3,y:3};
const fresh=()=>({stepCount:10,actorCooldown:{},stats:{patrolContacts:0}});
assert.equal(actorCtx.contactCheck([auditPatrol],district('old_market'),fresh()),true,'normal patrol detects the exposed crew');
assert.equal(actorCtx.contactCheck([auditPatrol],district('dock_nine'),fresh()),false,'disabled site audit changes actual patrol encounter gating');
assert.equal(encounters,1);
assert.match(streetsSource,/intelDistrictAftermathV134\(world\)/);
// The mutually exclusive ERASE branch changes watchlist recognition in the
// compromised district instead of pretending that physical patrols disappeared.
const eraseJob={id:'intel_followup_blacksite_77_erase',sectorId:'undergrid',intelFollowUpV14:{sourceMissionId:source.id,decision:'erase'}};
const eraseOutcome={id:`intel_outcome_${eraseJob.id}`,missionId:eraseJob.id,decision:'erase',districtId:'undergrid'};
const eraseGame={...game,missionHistory:[source,eraseJob],journal:[eraseOutcome],notoriety:45};
ctx.Game=eraseGame;actorCtx.Game=eraseGame;
assert.equal(ctx.calc(district('undergrid')).traceRelief,6);
assert.equal(ctx.calc(district('undergrid')).securityRelief,0);
assert.equal(ctx.calc(district('dock_nine')).closed,0,'old disclosure does not leak into separate erase campaign');
assert.ok(actorCtx.threat(patrol,district('undergrid'))<actorCtx.threat(patrol,district('dock_nine')));
ctx.Game=game;actorCtx.Game=game;
assert.match(streetsSource,/AUDIT RELAY OFFLINE/,'street HUD surfaces mission consequence');
console.log('PASS PWA12.79: persistent location-specific blacksite aftermath, nonstacking district relief, reduced patrol pressure, and readable street consequence');
