from pathlib import Path
import sys

root=Path(sys.argv[1]).resolve()
module=root/'src/world/interdistrict-logistics-pwa12-104-city-candidate-02.js'
module.write_text(r'''if(typeof window!=='undefined'){
(() => {
'use strict';
const VERSION='pwa12.104-city-candidate.02';
const KIND={courier:{label:'CITY COURIER',verb:'sealed courier case',base:420,heat:-1,prosperity:1},medical:{label:'CROSS-DISTRICT MEDICAL',verb:'temperature-locked medical case',base:520,heat:-2,prosperity:1},data:{label:'CROSS-DISTRICT DATA DROP',verb:'air-gapped data shard',base:590,heat:2,prosperity:0},contraband:{label:'INTERDISTRICT CONTRABAND',verb:'unregistered cargo case',base:720,heat:6,prosperity:0}};
const LINK_RISK={metro:.08,border:.18,freight:.24,security:.42,hidden:.06};
function clamp(v,a,b){return Math.max(a,Math.min(b,v))}
function hash(...parts){let h=2166136261>>>0;for(const x of parts){const s=String(x??'');for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}}return h>>>0}
function nowMin(){return Math.round((((Game.day||1)-1)*24+(Game.hour||0))*60)}
function state(){const s=window.ensureDistrictDispatchStateV12104?.();if(!s)return null;s.crossOffers=s.crossOffers||{};s.stats=s.stats||{};s.stats.crossAccepted=s.stats.crossAccepted||0;s.stats.crossDelivered=s.stats.crossDelivered||0;s.stats.crossAbandoned=s.stats.crossAbandoned||0;return s}
function world(){return window.currentDistrictV133?.()||null}
function defs(d){return window.V13_DISTRICT_LOCATIONS?.[d]||[]}
function def(d,id){return defs(d).find(x=>x.id===id)||null}
function known(d){return !!d&&(!!Game.cityLife?.discovered?.[d.id]||!!(d.contact&&Game.contactRelations?.[d.contact]?.known))}
function nearSource(w=world(),max=2.2){if(!w||!Game.ovPlayer)return null;let best=null;for(const d of defs(w.id)){const p=w.locations?.[d.id];if(!p||!known(d))continue;const q=Math.hypot(Game.ovPlayer.x-p.x,Game.ovPlayer.y-p.y);if(q<=max&&(!best||q<best.dist))best={id:d.id,def:d,point:p,dist:q}}return best}
function endpoint(link,district){return link?.from?.district===district?link.from:link?.to?.district===district?link.to:null}
function other(link,district){return link?.from?.district===district?link.to:link?.to?.district===district?link.from:null}
function linkVisible(link){if(!link)return false;if(link.type==='hidden')return !!Game.districtWorldsV133?.hiddenLinks?.[link.id];return true}
function directLinks(from,to){return (window.V133_TRANSIT_LINKS||[]).filter(l=>linkVisible(l)&&((l.from.district===from&&l.to.district===to)||(l.to.district===from&&l.from.district===to)))}
function nearestHood(w,p){let best=null,bd=Infinity;for(const n of w?.neighborhoods||[]){const d=Math.hypot((p.x||0)-n.x,(p.y||0)-n.y);if(d<bd){bd=d;best=n.id}}return best}
function hoodState(w,id){return window.ensureNeighborhoodStateV134?.(w)?.[id]||null}
function hoodRisk(h,kind){if(!h)return .3;const heat=(h.localHeat||0)/100,gang=(h.gangPressure||0)/5,unrest=(h.unrest||0)/5,sec=(h.security||0)/5;return clamp(heat*.30+gang*.24+unrest*.16+sec*((kind==='contraband'||kind==='data')?.30:.14),0,1)}
function pathRisk(w,path,kind){if(!path?.length)return .35;let sum=0,n=0,last=null;const step=Math.max(1,Math.floor(path.length/10));for(let i=0;i<path.length;i+=step){const hid=nearestHood(w,path[i]);if(hid===last)continue;last=hid;sum+=hoodRisk(hoodState(w,hid),kind);n++}return clamp(n?sum/n:.3,0,1)}
function typeFor(src,seed){if(src?.type==='clinic'||src?.shop&&String(src.shop).includes('clinic'))return ['medical','courier','data'][seed%3];if(src?.contact){const c=(window.V13_CONTACTS||[]).find(x=>x.id===src.contact),sv=c?.services||[];if(sv.includes('smuggling'))return ['contraband','courier','data'][seed%3];if(sv.includes('clinic'))return ['medical','data','courier'][seed%3]}return ['courier','data','contraband'][seed%3]}
function accessNote(link){const n=Game.notoriety||0,rep=Game.rep?.[link.faction]||0;if(link.type==='security'&&n>=58&&rep<25)return{label:'CHECKPOINT PRESSURE',risk:.18};if(link.type==='metro'&&n>=90)return{label:'WATCHLIST — BLOCKED',risk:.30,blocked:true};if(link.type==='hidden')return{label:'COVERT ROUTE',risk:-.04};if(link.type==='freight')return{label:'CARGO CONTROL',risk:.07};return{label:'CLEAR',risk:0}}
function optionQuote(sourceId,targetDistrict,targetId,link,kind,w=world()){
 if(!w||!link)return null;const se=endpoint(link,w.id),de=other(link,w.id);if(!se||de?.district!==targetDistrict)return null;const dw=window.generateDistrictV133?.(targetDistrict);if(!dw)return null;const sn=w.transit.find(t=>t.id===se.node),dn=dw.transit.find(t=>t.id===de.node),sp=w.locations?.[sourceId],tp=dw.locations?.[targetId];if(!sn||!dn||!sp||!tp)return null;
 const p1=window.findDistrictPathV133?.(sp,sn,w),p2=window.findDistrictPathV133?.(dn,tp,dw);if(!p1?.length||!p2?.length)return null;const access=accessNote(link),streetRisk=(pathRisk(w,p1,kind)+pathRisk(dw,p2,kind))/2,risk=clamp(streetRisk*.68+(LINK_RISK[link.type]??.2)+access.risk,0,1),blocks=Math.max(0,p1.length-1)+Math.max(0,p2.length-1),cost=link.cost||0,minutes=link.minutes||12;
 const spec=KIND[kind],payout=Math.round((spec.base+blocks*3.3+minutes*7+risk*330+cost*.45)/10)*10,windowMin=Math.max(45,Math.ceil(24+blocks*.34+minutes+risk*18));
 return{linkId:link.id,linkName:link.name,linkType:link.type,sourceNodeId:se.node,destinationNodeId:de.node,blocks,cost,transitMinutes:minutes,risk:Number(risk.toFixed(3)),payout,windowMin,accessLabel:access.label,blocked:!!access.blocked}
}
function quote(sourceId,targetDistrict,targetId,forcedKind=null,w=world()){
 const src=def(w?.id,sourceId),dst=def(targetDistrict,targetId);if(!w||!src||!dst||targetDistrict===w.id)return null;const seed=hash(w.id,sourceId,targetDistrict,targetId,Game.day||1),kind=forcedKind||typeFor(src,seed),options=directLinks(w.id,targetDistrict).map(l=>optionQuote(sourceId,targetDistrict,targetId,l,kind,w)).filter(Boolean);if(!options.length)return null;options.sort((a,b)=>a.blocked-b.blocked||a.risk-b.risk||a.windowMin-b.windowMin);return{kind,label:KIND[kind].label,verb:KIND[kind].verb,sourceDistrict:w.id,sourceId,sourceName:src.name,targetDistrict,targetId,targetName:dst.name,targetDistrictName:window.V133_DISTRICTS?.[targetDistrict]?.name||targetDistrict,options}}
window.quoteInterdistrictDispatchV12104=quote;
function offer(sourceId,w=world()){
 const s=state();if(!s||!w||!w.locations?.[sourceId])return null;const src=def(w.id,sourceId);if(!src||!known(src))return null;const key=`${w.id}:${sourceId}:${Game.day||1}:cross`;if(s.crossOffers[key])return s.crossOffers[key];
 const candidates=[];for(const td of Object.keys(window.V133_DISTRICTS||{})){if(td===w.id)continue;const links=directLinks(w.id,td);if(!links.length)continue;const dw=window.generateDistrictV133?.(td),targets=defs(td).filter(d=>dw?.locations?.[d.id]&&(d.contact||d.shop||d.type==='clinic'));for(const t of targets){const q=quote(sourceId,td,t.id,null,w);if(q)candidates.push(q)}}
 if(!candidates.length)return null;candidates.sort((a,b)=>{const ma=Math.min(...a.options.map(o=>o.risk)),mb=Math.min(...b.options.map(o=>o.risk));const av=a.options.filter(o=>!o.blocked).length,bv=b.options.filter(o=>!o.blocked).length;return (bv-av)||((hash(key,a.targetDistrict,a.targetId)%100000)-(hash(key,b.targetDistrict,b.targetId)%100000))||ma-mb});const pick=candidates[0],o={id:`cross_${w.id}_${Game.day||1}_${sourceId}`,day:Game.day||1,createdAt:nowMin(),...pick};s.crossOffers[key]=o;return o
}
window.offerInterdistrictDispatchV12104=offer;
function active(){const a=state()?.active;return a?.crossDistrict?a:null}
window.activeInterdistrictDispatchV12104=active;
function physicalSource(o,w=world()){const n=nearSource(w);return !!n&&n.id===o?.sourceId&&w?.id===o?.sourceDistrict}
function accept(id){const w=world(),n=nearSource(w),o=n?offer(n.id,w):null,s=state();if(!o||o.id!==id||s.active||!physicalSource(o,w))return false;const start=nowMin();s.active={...o,crossDistrict:true,status:'active',phase:'choose_transit',acceptedAt:start,deadline:null,chosenLinkId:null};s.stats.accepted=(s.stats.accepted||0)+1;s.stats.crossAccepted++;window.addJournal?.('side',o.label,`${o.sourceName} → ${o.targetName}, ${o.targetDistrictName}. Choose a physical transit leg before crossing the city.`);window.streetToastV134?.(`${o.label} · CHOOSE TRANSIT`);window.saveGame?.(0,true);update();return true}
window.acceptInterdistrictDispatchV12104=accept;
function choose(linkId){const a=active(),w=world();if(!a||!w||w.id!==a.sourceDistrict||a.phase==='last_mile')return false;const op=a.options.find(x=>x.linkId===linkId&&!x.blocked);if(!op)return false;a.chosenLinkId=linkId;a.chosenOption={...op};a.payout=op.payout;a.risk=op.risk;a.deadline=nowMin()+op.windowMin;a.phase='to_transit';const ok=window.routeToTransitNodeV133?.(op.sourceNodeId);if(!ok){a.phase='choose_transit';a.chosenLinkId=null;a.chosenOption=null;a.deadline=null;return false}window.streetToastV134?.(`${op.linkName} · ROUTE COMMITTED`);window.saveGame?.(0,true);update();return true}
window.chooseInterdistrictTransitV12104=choose;
function revealTarget(a){Game.cityLife=Game.cityLife||{};Game.cityLife.discovered=Game.cityLife.discovered||{};Game.cityLife.discovered[a.targetId]=true}
function transitComplete(ctx){const a=active();if(!a||ctx?.fromDistrict!==a.sourceDistrict||ctx?.toDistrict!==a.targetDistrict)return;const op=a.options.find(x=>x.linkId===ctx.linkId);if(!op)return;a.chosenLinkId=op.linkId;a.chosenOption={...op};a.payout=op.payout;a.risk=op.risk;if(!a.deadline)a.deadline=nowMin()+op.windowMin;a.transitMode=ctx.mode||'clear';a.transitAt=nowMin();a.phase='last_mile';revealTarget(a);setTimeout(()=>{window.routeToLocationV133?.(a.targetId);update()},0);window.addJournal?.('side','CITY TRANSIT LEG',`${op.linkName} crossed via ${String(ctx.mode||'clear').toUpperCase()}. Last-mile route opened to ${a.targetName}.`);window.saveGame?.(0,true)}
window.onDistrictTransitCompleteV12104=transitComplete;
function mutate(h,field,delta){if(!h)return;if(field==='localHeat')h[field]=clamp((h[field]||0)+delta,0,100);else h[field]=clamp((h[field]||0)+delta,0,5);h.events=(h.events||0)+1}
function complete(w=world()){
 const s=state(),a=active();if(!a||!w||a.phase!=='last_mile'||w.id!==a.targetDistrict)return false;const p=w.locations?.[a.targetId];if(!p||!Game.ovPlayer||Math.hypot(Game.ovPlayer.x-p.x,Game.ovPlayer.y-p.y)>2.15)return false;const spec=KIND[a.kind]||KIND.courier,now=nowMin(),late=Math.max(0,now-(a.deadline||now)),mult=late?Math.max(.4,1-Math.min(1,late/120)*.6):1,reward=Math.round(a.payout*mult/10)*10,hs=hoodState(w,p.neighborhood);Game.credits=(Game.credits||0)+reward;mutate(hs,'localHeat',spec.heat);if(spec.prosperity)mutate(hs,'prosperity',spec.prosperity);if(a.kind==='medical')mutate(hs,'unrest',-1);if(a.kind==='contraband'&&a.chosenOption?.linkType==='security')mutate(hs,'localHeat',3);
 const src=def(a.sourceDistrict,a.sourceId);if(src?.contact&&Game.contactRelations?.[src.contact]?.known&&typeof window.changeContactTrustV13==='function')window.changeContactTrustV13(src.contact,late?-1:1,late?'Late interdistrict dispatch':'Completed interdistrict dispatch');const rec={...a,status:'delivered',deliveredAt:now,lateMinutes:late,reward};s.history.unshift(rec);s.history=s.history.slice(0,24);s.active=null;s.stats.delivered=(s.stats.delivered||0)+1;s.stats.crossDelivered++;if(late)s.stats.late=(s.stats.late||0)+1;window.streetToastV134?.(`${a.label} ${late?'LATE':'DELIVERED'} · ¢${reward}`);window.addJournal?.('side',`${a.label} ${late?'LATE':'DELIVERED'}`,`${a.targetName} received ${a.verb}. Transit: ${a.chosenOption?.linkName||'city route'}. Paid ¢${reward}.`);window.updateNeighborhoodHUDV134?.();window.updateOverworldHUD?.();window.saveGame?.(0,true);update();return rec
}
window.tryCompleteInterdistrictDispatchV12104=complete;
function abandon(){const s=state(),a=active();if(!a)return false;const src=def(a.sourceDistrict,a.sourceId);if(src?.contact&&Game.contactRelations?.[src.contact]?.known&&typeof window.changeContactTrustV13==='function')window.changeContactTrustV13(src.contact,-1,'Abandoned interdistrict dispatch');s.history.unshift({...a,status:'abandoned',endedAt:nowMin()});s.history=s.history.slice(0,24);s.active=null;s.stats.abandoned=(s.stats.abandoned||0)+1;s.stats.crossAbandoned++;Game.pendingPath=null;Game._v133TravelTarget=null;window.streetToastV134?.('INTERDISTRICT RUN ABANDONED');window.saveGame?.(0,true);update();return true}
window.abandonInterdistrictDispatchV12104=abandon;
function riskLabel(r){return r>=.72?'SEVERE':r>=.52?'HIGH':r>=.32?'ELEVATED':'MANAGEABLE'}
function panel(){let p=document.getElementById('v12104-interdistrict-panel');const wrap=document.querySelector('#overworld-screen .wrap');if(!wrap)return null;if(!document.getElementById('v12104-interdistrict-style')){const st=document.createElement('style');st.id='v12104-interdistrict-style';st.textContent=`#v12104-interdistrict-panel{position:absolute;right:14px;bottom:84px;z-index:26;width:min(360px,calc(100% - 28px));max-height:min(62vh,510px);overflow:auto;padding:11px 12px;background:rgba(5,11,15,.97);border:1px solid rgba(255,176,58,.48);box-shadow:0 9px 28px rgba(0,0,0,.5);font:12px/1.35 monospace;color:#d8edf2;display:none;pointer-events:auto}#v12104-interdistrict-panel .k{font-size:10px;letter-spacing:.13em;color:#ffb03a}#v12104-interdistrict-panel .meta{margin:6px 0;color:#aebdc2}#v12104-interdistrict-panel .choice{margin:7px 0;padding:7px;border:1px solid rgba(255,255,255,.11)}#v12104-interdistrict-panel .terms{display:grid;grid-template-columns:repeat(3,1fr);gap:4px;margin:6px 0}#v12104-interdistrict-panel .terms span{padding:4px;background:rgba(255,255,255,.04);text-align:center}#v12104-interdistrict-panel button{width:100%;min-height:40px;margin-top:4px}@media(max-width:520px){#v12104-interdistrict-panel{left:8px;right:8px;bottom:76px;width:auto;max-height:56vh;padding:9px 10px}#v12104-interdistrict-panel button{min-height:44px}}`;document.head.appendChild(st)}if(!p){p=document.createElement('div');p.id='v12104-interdistrict-panel';wrap.appendChild(p)}return p}
function update(){const p=panel(),w=world();if(!p||Game.screen!=='overworld-screen'||!w){if(p)p.style.display='none';return}const s=state(),a=active(),local=document.getElementById('v12104-dispatch-panel');if(a){if(local)local.style.display='none';p.style.display='block';const remain=a.deadline===null?null:a.deadline-nowMin();let body=`<div class="k">ACTIVE INTERDISTRICT RUN</div><b>${a.label}</b><div class="meta">${a.sourceName} → ${a.targetName}<br>${a.targetDistrictName} · ${a.verb}${remain===null?'':` · ${remain>=0?remain+' MIN LEFT':Math.abs(remain)+' MIN LATE'}`}</div>`;if(a.phase==='choose_transit'){body+=`<div class="meta">Choose the city leg. Each option is a real transit node you must physically reach.</div>`+a.options.map(o=>`<div class="choice"><b>${o.linkName}</b> · ${o.linkType.toUpperCase()}<div class="terms"><span>¢${o.payout}<br>PAYOUT</span><span>${riskLabel(o.risk)}<br>RISK</span><span>${o.cost?`¢${o.cost}`:'FREE'}<br>FARE</span></div><div class="meta">${o.blocks} street cells + ${o.transitMinutes} min · ${o.accessLabel}</div><button class="btn small" data-cross-link="${o.linkId}" ${o.blocked?'disabled':''}>${o.blocked?'UNAVAILABLE':'ROUTE VIA '+o.linkType.toUpperCase()}</button></div>`).join('')}else if(a.phase==='to_transit'){const o=a.chosenOption;body+=`<div class="choice"><b>FIRST LEG · ${o.linkName}</b><div class="meta">Reach the marked ${o.linkType} node physically, then use the normal transit controls. Existing checkpoint/bribe/hack rules remain authoritative.</div><div class="terms"><span>¢${a.payout}<br>PAYOUT</span><span>${riskLabel(a.risk)}<br>RISK</span><span>${o.transitMinutes}<br>TRANSIT MIN</span></div></div>`}else{const target=w.id===a.targetDistrict?w.locations?.[a.targetId]:null,dist=target&&Game.ovPlayer?Math.round(Math.hypot(Game.ovPlayer.x-target.x,Game.ovPlayer.y-target.y)):null;body+=`<div class="choice"><b>LAST MILE · ${a.chosenOption?.linkName||'CITY TRANSIT'}</b><div class="meta">Transit complete. Deliver physically at ${a.targetName}.</div><div class="terms"><span>¢${a.payout}<br>PAYOUT</span><span>${riskLabel(a.risk)}<br>RISK</span><span>${dist===null?'—':dist}<br>CELLS</span></div><button class="btn small" id="v12104-cross-route-last">ROUTE TO DROP</button></div>`}body+=`<button class="btn small" id="v12104-cross-abandon">ABANDON RUN</button>`;p.innerHTML=body;p.querySelectorAll('[data-cross-link]').forEach(b=>b.onclick=()=>choose(b.dataset.crossLink));p.querySelector('#v12104-cross-route-last')?.addEventListener('click',()=>{if(w.id===a.targetDistrict)window.routeToLocationV133?.(a.targetId);else window.openStrategicCityMapV133?.()});p.querySelector('#v12104-cross-abandon').onclick=()=>abandon();return}
 const n=nearSource(w);if(!n){p.style.display='none';return}const o=offer(n.id,w);if(!o){p.style.display='none';return}p.style.display='block';if(local)local.style.display='none';const best=o.options.find(x=>!x.blocked)||o.options[0];p.innerHTML=`<div class="k">${w.cfg.name.toUpperCase()} // CITY LOGISTICS</div><b>${o.label}</b><div class="meta">Pickup at ${o.sourceName}. Deliver a ${o.verb} to <b>${o.targetName}</b> in <b>${o.targetDistrictName}</b>. Transit leg is your choice after acceptance.</div><div class="terms"><span>${o.options.length}<br>ROUTES</span><span>¢${best?.payout||0}<br>FROM PAYOUT</span><span>${riskLabel(best?.risk||0)}<br>BEST RISK</span></div><button class="btn small" id="v12104-cross-accept">ACCEPT CITY RUN</button>`;p.querySelector('#v12104-cross-accept').onclick=()=>accept(o.id)}
window.updateInterdistrictDispatchUIV12104=update;
const prevStep=window.onStreetStepV134;window.onStreetStepV134=function(w){const r=prevStep?.apply(this,arguments);complete(w||world());update();return r};
const prevInit=window.initOverworldV133;if(prevInit){const wrapped=function(){const r=prevInit.apply(this,arguments);complete(world());update();return r};window.initOverworldV133=wrapped;if(window.initOverworld===prevInit)window.initOverworld=wrapped}
setTimeout(update,0);window.CR_CITY_INTERDISTRICT_LOGISTICS={version:VERSION,update};
})();
}''',encoding='utf-8')

# Minimal optional hook at the canonical transit success seam. Existing transit
# access, fare, time, notoriety, activation, and save behavior remain authoritative.
p=root/'src/world/district-worlds-v13-3.js'
s=p.read_text(encoding='utf-8')
needle="initOverworldV133();toast(`${V133_DISTRICTS[current].name} → ${V133_DISTRICTS[to.district].name}`);saveGame(0,true);return true"
repl="initOverworldV133();toast(`${V133_DISTRICTS[current].name} → ${V133_DISTRICTS[to.district].name}`);window.onDistrictTransitCompleteV12104?.({linkId:link.id,link,fromDistrict:current,toDistrict:to.district,fromNode:ep.node,toNode:to.node,mode,cost});saveGame(0,true);return true"
if needle not in s: raise SystemExit('transit success seam missing')
s=s.replace(needle,repl,1)
p.write_text(s,encoding='utf-8')

manifest=root/'src/bootstrap/module-manifest.js'
s=manifest.read_text(encoding='utf-8')
entry="  'world.interdistrictLogistics':{path:'./src/world/interdistrict-logistics-pwa12-104-city-candidate-02.js',kind:'module'},\n"
if 'world.interdistrictLogistics' not in s:
    needle="  'world.districtDispatches':{path:'./src/world/district-dispatches-pwa12-104-city-candidate-01.js',kind:'module'},\n"
    if needle not in s: raise SystemExit('district dispatch manifest seam missing')
    s=s.replace(needle,needle+entry,1)
    order="'world.livingStreets','world.districtDispatches','missions.approaches'"
    if order not in s: raise SystemExit('manifest order seam missing')
    s=s.replace(order,"'world.livingStreets','world.districtDispatches','world.interdistrictLogistics','missions.approaches'",1)
manifest.write_text(s,encoding='utf-8')
print('patched interdistrict logistics candidate',root)
