from pathlib import Path
import sys
root=Path(sys.argv[1]).resolve()
p=root/'src/world/interdistrict-logistics-pwa12-104-city-candidate-02.js'
s=p.read_text(encoding='utf-8')
s=s.replace("function update(){const p=panel(),w=world();", "let boardOpen=false;\nwindow.openInterdistrictDispatchBoardV12104=function(){boardOpen=true;update();return true};\nwindow.closeInterdistrictDispatchBoardV12104=function(){boardOpen=false;update();return true};\nfunction update(){const p=panel(),w=world();",1)
old="const n=nearSource(w);if(!n){p.style.display='none';return}const o=offer(n.id,w);if(!o){p.style.display='none';return}p.style.display='block';if(local)local.style.display='none';const best=o.options.find(x=>!x.blocked)||o.options[0];p.innerHTML=`<div class=\"k\">${w.cfg.name.toUpperCase()} // CITY LOGISTICS</div><b>${o.label}</b><div class=\"meta\">Pickup at ${o.sourceName}. Deliver a ${o.verb} to <b>${o.targetName}</b> in <b>${o.targetDistrictName}</b>. Transit leg is your choice after acceptance.</div><div class=\"terms\"><span>${o.options.length}<br>ROUTES</span><span>¢${best?.payout||0}<br>FROM PAYOUT</span><span>${riskLabel(best?.risk||0)}<br>BEST RISK</span></div><button class=\"btn small\" id=\"v12104-cross-accept\">ACCEPT CITY RUN</button>`;p.querySelector('#v12104-cross-accept').onclick=()=>accept(o.id)}"
new="const n=nearSource(w);if(!n){p.style.display='none';boardOpen=false;return}const o=offer(n.id,w);if(!o){p.style.display='none';return}if(!boardOpen){p.style.display='none';if(local&&local.style.display!=='none'&&!local.querySelector('#v12104-open-city-run')){const b=document.createElement('button');b.className='btn small';b.id='v12104-open-city-run';b.textContent='INTERDISTRICT RUN';b.onclick=()=>{boardOpen=true;update()};(local.querySelector('.actions')||local).appendChild(b)}return}p.style.display='block';if(local)local.style.display='none';const best=o.options.find(x=>!x.blocked)||o.options[0];p.innerHTML=`<div class=\"k\">${w.cfg.name.toUpperCase()} // CITY LOGISTICS</div><b>${o.label}</b><div class=\"meta\">Pickup at ${o.sourceName}. Deliver a ${o.verb} to <b>${o.targetName}</b> in <b>${o.targetDistrictName}</b>. Transit leg is your choice after acceptance.</div><div class=\"terms\"><span>${o.options.length}<br>ROUTES</span><span>¢${best?.payout||0}<br>FROM PAYOUT</span><span>${riskLabel(best?.risk||0)}<br>BEST RISK</span></div><button class=\"btn small\" id=\"v12104-cross-accept\">ACCEPT CITY RUN</button><button class=\"btn small\" id=\"v12104-cross-local\">BACK TO LOCAL BOARD</button>`;p.querySelector('#v12104-cross-accept').onclick=()=>accept(o.id);p.querySelector('#v12104-cross-local').onclick=()=>{boardOpen=false;p.style.display='none';window.updateDistrictDispatchUIV12104?.();update()}}"
if old not in s: raise SystemExit('interdistrict offer UI seam missing')
s=s.replace(old,new,1)
p.write_text(s,encoding='utf-8')
print('preserved local dispatch board with explicit interdistrict toggle')
