from pathlib import Path
import json,sys
root=Path(sys.argv[1] if len(sys.argv)>1 else '.').resolve()
mod=(root/'src/world/patrol-routing-pwa12-104-city-candidate-08.js').read_text(encoding='utf-8')
district=(root/'src/world/district-worlds-v13-3.js').read_text(encoding='utf-8')
manifest=(root/'src/bootstrap/module-manifest.js').read_text(encoding='utf-8')
bundle=(root/'src/runtime/runtime-bundle.js').read_text(encoding='utf-8')
meta=json.loads((root/'build-meta.json').read_text(encoding='utf-8')) if (root/'build-meta.json').exists() else {}
checks=[]
def ck(label,cond):checks.append((label,bool(cond)))
ck('versioned Candidate 08 module exists',"pwa12.104-city-candidate.08" in mod)
ck('persistent state stays under Living Streets',"s.patrolRouting=s.patrolRouting||" in mod and "ensureLivingStreetsStateV134" in mod)
ck('active physical route is persisted',"activeRoute:null" in mod and "resumePatrolRouteV12104" in mod)
ck('history remains bounded',"slice(0,48)" in mod)
ck('route profiles are FAST LOW PROFILE BACK ALLEY',all(x in mod for x in ["name:'FAST'","name:'LOW PROFILE'","name:'BACK ALLEY'"]))
ck('canonical terrain classes are represented',all(x in mod for x in ['ART:1','SEC:2','ALLEY:3','TUNNEL:10','INDUSTRIAL:12','PED:13','TRANSIT:14']))
ck('FAST delegates to canonical A-star',"profile==='fast'" in mod and "findDistrictPathV133" in mod)
ck('LOW PROFILE has security and gang exposure weights',"low:{security:5.2,gang:3.5}" in mod)
ck('BACK ALLEY materially favors alley and tunnel terrain',"[T.ALLEY]:.58" in mod and "[T.TUNNEL]:.58" in mod)
ck('BACK ALLEY penalizes security and transit terrain',"[T.SEC]:1.82" in mod and "[T.TRANSIT]:1.70" in mod)
ck('risk-aware A-star preserves diagonal corner safety',"dx&&dy&&(!walkable" in mod)
ck('risk-aware A-star uses physical world terrain',"world.terrain" in mod and "BASE[world.terrain[idx]]" in mod)
ck('patrol corridors derive from local heat and security',"h.localHeat" in mod and "h.security" in mod)
ck('patrol corridors derive from gang pressure and unrest',"h.gangPressure" in mod and "h.unrest" in mod)
ck('physical control posts project corridor influence',"controlPostsForWorldV12104" in mod and "controlPost:true" in mod)
ck('corridors are anchored to real neighborhoods',"world.neighborhoods" in mod and "neighborhood:n.id" in mod)
ck('corridors use real transit/location coordinates',"world.transit" in mod and "world.locations" in mod)
ck('risk grid distinguishes security and gang exposure',"security=new Float32Array" in mod and "gang=new Float32Array" in mod)
ck('planner reports physical path cells and exposure',"cells:Math.max(0,n-1)" in mod and "exposure:" in mod and "hotCells" in mod)
ck('planner computes all three actual route geometries',"findRiskPath(Game.ovPlayer,goal,'fast'" in mod and "findRiskPath(Game.ovPlayer,goal,'low'" in mod and "findRiskPath(Game.ovPlayer,goal,'back'" in mod)
ck('route planner is player-facing and names active patrol corridors',"ROUTE TACTICS" in mod and "ACTIVE PATROL CORRIDORS" in mod)
ck('planner explains system inputs to player',all(x in mod for x in ['Local Heat','Security','Gang Pressure','Unrest']))
ck('route preview draws patrol corridors on physical map',"drawPatrolRoutingV12104" in mod and "pointSegDist" in mod)
ck('route preview draws all three candidate paths',all(x in mod for x in ["PREVIEW.plans.fast","PREVIEW.plans.low","PREVIEW.plans.back"]))
ck('manual marker taps invoke route planner',"openPatrolRoutePlannerV12104?.({x:mark.x,y:mark.y}" in district)
ck('manual free-point taps invoke route planner',"openPatrolRoutePlannerV12104?.(q,rt)" in district)
ck('programmatic routeToLocation remains present',"function routeToLocationV133" in district)
ck('programmatic routeToTransit remains present',"function routeToTransitNodeV133" in district)
ck('canonical route authority accepts one-shot route override',"takePatrolRouteOverrideV12104" in district)
ck('canonical route authority remains responsible for pendingPath',"Game.pendingPath=path" in district)
ck('canonical scheduler still wakes selected route',"scheduleOverworldFrameV133(0)" in district)
ck('canonical camera/route-card lifecycle remains intact',"updateRouteCardV133();updateCameraModeV133()" in district)
ck('route commit callback records persistence without teleport',"onPhysicalRouteCommittedV12104" in district and "Game.ovPlayer={" not in mod and "Game.ovPlayer =" not in mod)
ck('save-load resume recomputes risk-aware path from restored player position',"resumeActive" in mod and "planRoutes(a.goal,a.target,w)" in mod)
ck('resume yields to control-post/transit-incident objectives',"controlPosts?.approach" in mod and "transitIncidents?.active" in mod)
ck('street-step chain records exposure without replacing Living Streets',"const prevStep=window.onStreetStepV134" in mod and "prevStep.apply" in mod)
ck('draw chain preserves Living Streets renderer',"const prevDraw=window.drawLivingStreetsV134" in mod and "prevDraw.apply" in mod)
ck('mobile panel is viewport bounded',"width:min(430px,calc(100vw - 24px))" in mod and "width:calc(100vw - 20px)" in mod)
ck('mobile controls meet touch target floor',"min-height:64px" in mod and "min-height:46px" in mod)
ck('module registered in manifest',"'world.patrolRouting'" in manifest and "patrol-routing-pwa12-104-city-candidate-08.js" in manifest)
order=[manifest.find("'world.accessEcology'"),manifest.find("'world.transitIncidents'"),manifest.find("'world.controlPosts'"),manifest.find("'world.patrolRouting'"),manifest.find("'missions.approaches'")]
ck('manifest order preserves cumulative city authorities',all(x>=0 for x in order) and order==sorted(order))
markers=['/* SOURCE: src/world/district-control-posts-pwa12-104-city-candidate-07.js */','/* SOURCE: src/world/patrol-routing-pwa12-104-city-candidate-08.js */','/* SOURCE: src/missions/contract-approaches-v13-4b.js */']
pos=[bundle.find(x) for x in markers]
ck('runtime source order places Candidate 08 after Candidate 07',all(x>=0 for x in pos) and pos==sorted(pos))
if meta:
 ck('production version stamped Candidate 08',meta.get('version')=='14.0.0-pwa.12.104-city-patrol-routing-candidate.08')
 ck('save schema remains 14',meta.get('schemaVersion')==14)
failed=[x for x in checks if not x[1]]
for label,ok in checks:print(('PASS' if ok else 'FAIL'),label)
if failed:raise SystemExit(f'{len(failed)} Candidate 08 contract checks failed: {[x[0] for x in failed]}')
print(f'PASS Candidate 08 Patrol Corridors + Risk-Aware Routing contract: {len(checks)} checks')