from pathlib import Path
import json,sys
root=Path(sys.argv[1] if len(sys.argv)>1 else '.').resolve()
mod=(root/'src/world/district-control-posts-pwa12-104-city-candidate-07.js').read_text(encoding='utf-8')
manifest=(root/'src/bootstrap/module-manifest.js').read_text(encoding='utf-8')
bundle=(root/'src/runtime/runtime-bundle.js').read_text(encoding='utf-8')
district=(root/'src/world/district-worlds-v13-3.js').read_text(encoding='utf-8')
meta=json.loads((root/'build-meta.json').read_text(encoding='utf-8')) if (root/'build-meta.json').exists() else {}
checks=[]
def ck(label,cond):checks.append((label,bool(cond)))
ck('versioned Candidate 07 module exists',"pwa12.104-city-candidate.07" in mod)
ck('persistent state lives under Living Streets',"s.controlPosts=s.controlPosts||" in mod and "ensureLivingStreetsStateV134" in mod)
ck('state includes approach persistence',"approach:null" in mod and "resumeControlPostApproachV12104" in mod)
ck('state includes one-crossing clearances',"clearances:{}" in mod and "consumed:false" in mod and "c.consumed=true" in mod)
ck('state includes temporary suppression after violence',"suppressed:{}" in mod and "nowMin()+180" in mod)
ck('bounded history is maintained',"slice(0,48)" in mod)
ck('posts derive from live Access Ecology',"evaluateTransitAccessEcologyV12104" in mod and "free_roam" in mod)
ck('live heat/security/gang/unrest drive posts',all(x in mod for x in ["p.security","p.gang","p.heat","riskDelta","minutesDelta","costDelta"]))
ck('hidden/covert routes are not exposed as control posts',"l.type==='hidden'" in mod)
ck('Candidate 06 owns matching logistics incidents',"candidate06Owns" in mod and "transitIncidents" in mod)
ck('physical placement comes from real transit node',"nodeForLink" in mod and "x:n.x,y:n.y" in mod)
ck('physical neighborhood is resolved at post coordinate',"nearestHood" in mod and "neighborhood:nearestHood" in mod)
ck('posts enumerate actual world transit links',"for(const tr of w.transit||[])" in mod and "tr.linkIds" in mod)
ck('physical approach uses canonical A-star pathfinder',"findDistrictPathV133" in mod)
ck('physical approach writes Game.pendingPath',"Game.pendingPath=path" in mod)
ck('control-post target is explicit',"kind:'v12104controlpost'" in mod)
ck('no player-position teleport assignment exists',"Game.ovPlayer={" not in mod and "Game.ovPlayer =" not in mod)
ck('map drawing is layered through Living Streets',"const prevDraw=window.drawLivingStreetsV134" in mod and "drawControlPostsV12104" in mod)
ck('map taps route or open the physical post',"handleControlPostTapV12104" in mod and "postNear(q)" in mod)
ck('street-step arrival detection exists',"const prevStep=window.onStreetStepV134" in mod and "detect();" in mod)
ck('save/load overworld initialization reconstructs approach',"const prevInit=window.initOverworldV133" in mod and "setTimeout(()=>{resume();detect()}" in mod)
ck('ordinary transit-node opening is physically intercepted',"interceptControlPostTransitNodeV12104" in district)
ck('lexical canonical travel has pre-crossing control-post gate',"prepareControlPostTransitV12104" in district)
ck('canonical successful crossing consumes Candidate 07 clearance',"commitControlPostTransitV12104" in district)
ck('normal canonical transit authority remains present',"function travelDistrictV133(linkId,mode='clear')" in district and "activateDistrictV133(to.district,to.node)" in district)
ck('nonviolent compliance changes money/time/local conditions',"Game.credits" in mod and "advanceTime?.(p.profile.delay)" in mod and "mutate(p" in mod)
ck('AgentEX credential play exists',"AGENTEX · CREDENTIAL PLAY" in mod and "kind==='agentex'" in mod)
ck('Hacker spoof exists with faction/local consequences',"HACKER · SPOOF CONTROL" in mod and "factionHeat(p,3)" in mod)
ck('violent resolution uses established street-combat bridge',"launchStreetCombatV134" in mod and "onTransitIncidentStreetCombatSettledV12104" in mod)
ck('combat hook chains Candidate 06 instead of replacing it',"const prevCombatHook=window.onTransitIncidentStreetCombatSettledV12104" in mod and "prevCombatHook?.apply" in mod)
ck('retreat clears the route without teleporting',"BACK OFF" in mod and "Game.pendingPath=null" in mod and "retreated" in mod)
ck('fight success suppresses post and grants one crossing',"method:'fight'" in mod and "CONTROL POST BROKEN" in mod and "suppressedUntil" in mod)
ck('clearance does not claim to bypass canonical security',"does not bypass the crossing's normal faction/security requirements" in mod)
ck('mobile panel width is viewport bounded',"width:min(390px,calc(100vw - 24px))" in mod and "width:calc(100vw - 20px)" in mod)
ck('mobile actions meet minimum touch target',"min-height:44px" in mod and "min-height:46px" in mod)
ck('module is registered in manifest',"'world.controlPosts'" in manifest and "district-control-posts-pwa12-104-city-candidate-07.js" in manifest)
order=[manifest.find("'world.accessEcology'"),manifest.find("'world.transitIncidents'"),manifest.find("'world.controlPosts'"),manifest.find("'missions.approaches'")]
ck('module manifest order is Access Ecology -> Transit Incidents -> Control Posts -> missions',all(x>=0 for x in order) and order==sorted(order))
markers=['/* SOURCE: src/world/access-ecology-pwa12-104-city-candidate-05.js */','/* SOURCE: src/world/transit-incidents-pwa12-104-city-candidate-06.js */','/* SOURCE: src/world/district-control-posts-pwa12-104-city-candidate-07.js */','/* SOURCE: src/missions/contract-approaches-v13-4b.js */']
pos=[bundle.find(x) for x in markers]
ck('runtime source order contains Candidate 07 at correct seam',all(x>=0 for x in pos) and pos==sorted(pos))
if meta:
 ck('production version stamped Candidate 07',meta.get('version')=='14.0.0-pwa.12.104-city-control-posts-candidate.07')
 ck('save schema remains 14',meta.get('schemaVersion')==14)
failed=[x for x in checks if not x[1]]
for label,ok in checks:print(('PASS' if ok else 'FAIL'),label)
if failed:raise SystemExit(f'{len(failed)} Candidate 07 contract checks failed: {[x[0] for x in failed]}')
print(f'PASS Candidate 07 District Control Posts contract: {len(checks)} checks')
